/**
 * The `jest-expo` preset supplies the Expo/React Native transform, module
 * mocks and platform resolution; everything below is project-specific.
 */
module.exports = {
  preset: 'jest-expo',
  moduleNameMapper: {
    // Mirrors the `@/*` path alias in tsconfig.json so tests import modules by
    // exactly the same specifier the app does.
    '^@/(.*)$': '<rootDir>/src/$1',
  },
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  // Every resource the tests own is torn down explicitly (the hook is unmounted,
  // each QueryClient is unmounted and cleared, and the persisted store singleton
  // is deliberately not imported — see src/store/configureStore.ts). What is left
  // holding the event loop open lives inside the React Native test renderer that
  // @testing-library/react-native 14 sits on, which this combination of RN 0.86 /
  // RNTL 14 does not release. Without this flag `npm test` reports every suite
  // green and then hangs for ~2 minutes, which would be worse in CI than the flag.
  forceExit: true,
  // Redux Toolkit, react-redux and redux-persist ship ESM-only builds that Jest
  // cannot `require`. This is jest-expo's default allowlist with those three
  // appended, so they get compiled to CommonJS by babel-jest like RN packages do.
  transformIgnorePatterns: [
    '/node_modules/(?!(.pnpm|react-native|@react-native|@react-native-community|expo|@expo|@expo-google-fonts|react-navigation|@react-navigation|@sentry/react-native|native-base|standard-navigation|@reduxjs/toolkit|react-redux|redux-persist|redux|immer|reselect))',
    '/node_modules/react-native-reanimated/plugin/',
    '/node_modules/@react-native/babel-preset/',
  ],
  testMatch: ['<rootDir>/src/**/__tests__/**/*.test.ts?(x)'],
  collectCoverageFrom: [
    'src/**/*.{ts,tsx}',
    // Vendored gluestack primitives are generated by `gluestack-ui add`; they
    // are the library's code, not ours, so they do not count towards coverage.
    '!src/components/ui/**',
    '!src/**/__tests__/**',
    '!src/**/*.d.ts',
  ],
};
